/*
 * Generated by MTK SP Drv_CodeGen Version 10.03.0 for MT6589_NP. Copyright MediaTek Inc. (C) 2012.
 * Fri Aug  8 20:09:26 2014
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


